src/core/UsingWrapper.js, src/core/index.js, src/core/update.js, src/core/using.js, src/core/using.spec.js, src/seq/ChainWrapper.js
=> core.using first version

src/object/index.js, src/object/pickBy.js, src/object/pickBy.spec.js
=> Add object.pickBy

src/array/index.js, src/array/splice.js, src/array/splice.spec.js, src/array/unshift.js, src/array/unshift.spec.js
=> Add Array functions (splice and unshift)

src/array/push.js, src/array/splice.js, src/array/unshift.js, src/array/xor.js, src/collection/map.js, src/lang/toggle.js, src/math/add.js, src/object/assign.js, src/object/mapValues.js, src/object/pickBy.js, src/object/update.js, src/object/update.spec.js, src/util/UsingWrapper.js, src/util/convert.js, src/util/convert.spec.js, src/util/index.js
=> :hammer: Replace object.update(fn) by util.convert(fn)

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> Contributing guidelines

package-lock.json, package.json, yarn.lock
=> Upgrade dependencies and add npm 5 package-lock.json

src/array/unshift.js
Fixing unshift documentation examples
**Issue :** fix #43
=> Fixing unshift documentation examples

README.md
Add a documentation badge in README.md
=> :memo: Add a documentation badge

src/array/concat.js, src/array/concat.spec.js, src/array/difference.js, src/array/difference.spec.js, src/array/drop.js, src/array/drop.spec.js, src/array/index.js, src/array/pull.js, src/array/pull.spec.js, src/array/push.js, src/array/remove.js, src/array/remove.spec.js, src/array/splice.js, src/array/unshift.js, src/array/xor.js
=> Add lodash array functions

.babelrc, package-lock.json, package.json, yarn.lock
=> Go back to babel preset stage-2 instead of stage-0

src/array/index.js, src/array/take.js, src/array/take.spec.js, src/array/takeRight.js, src/array/takeRight.spec.js, src/array/takeRightWhile.js, src/array/takeRightWhile.spec.js, src/array/takeWhile.js, src/array/takeWhile.spec.js
**Issue :** [#49]
take:
```js
take({ nested: { prop: [1, 2, 3, 4] } }, 'nested.prop', 2) 
// => { nested: { prop: [1, 2] } }
```
takeRight:
```js
takeRight({ nested: { prop: [1, 2, 3, 4] } }, 'nested.prop', 2) 
// => { nested: { prop: [3, 4] } }
```
takeRightWhile:
```js
takeRightWhile({ nested: { prop: [1, 2, 3, 4] } }, 'nested.prop', v => v > 3) 
// => { nested: { prop: [4] } }
```
takeWhile:
```js
takeWhile({ nested: { prop: [1, 2, 3, 4] } }, 'nested.prop', v => v < 2) 
// => { nested: { prop: [1] } }
```
=> Add lodash take, takeRight, takeRightWhile, takeWhile functions

package-lock.json, package.json, src/.eslintrc.json, src/seq/ChainWrapper.js, src/util/UsingWrapper.js, yarn.lock
Trailing commas in functions
**Issue :** #56
=> :hammer: Trailing commas in functions fix #56

src/math/divide.js, src/math/divide.spec.js, src/math/index.js, src/math/multiply.js, src/math/multiply.spec.js, src/math/subtract.js, src/math/subtract.spec.js
=> Add lodash math functions

src/util/protect.js, src/util/protect.spec.js
The purpose of `protect` is to prevent mutations on an object by wrapping it in a proxy, then allow to get the result of the mutations performed on the proxy.
It uses a chain sequence to store the operations performed on the proxy.
```js
const object = {
a: 1,
b: { c: 3 },
}
protect(object)(protectedObject => {
// protectedObject is a proxy which protects object from mutations
protectedObject.a++
protectedObject.b.d = protectedObject.a * protectedObject.b.c
delete protectedObject.b.c
}) // => { a: 2, b: { d: 6 } }
```
=> Experimenting protect feature

src/string/index.js
Fix typo described in issue #91
=> :bug: Fix typo in capitalize name

circle.yml, publish-docs.sh
See circle build fails https://circleci.com/gh/Zenika/immutadot/352
=> fix documentation publication

package-lock.json, package.json, yarn.lock
babel 6.24.1 -> 6.26.0
eslint 4.4.1 -> 4.6.1
jest 21.0.0 -> 21.0.1
=> Upgrade dependencies

src/seq/ChainWrapper.js, src/util/UsingWrapper.js
=> Add string namespace to seq.chain and util.using

src/core/apply.js, src/core/convert.js, src/core/set.js, src/core/unset.js, src/core/update.js
=> Small refactorings in core

packages/immutadot/src/core/apply.js, packages/immutadot/src/core/apply.spec.js, packages/immutadot/src/core/path.utils.js, packages/immutadot/src/core/path.utils.spec.js, packages/immutadot/src/flow/flow.js
=> ⚡ flow: Avoid multiple reinstanciations

packages/immutadot/src/core/apply.js, packages/immutadot/src/core/apply.spec.js
Handle error when an empty path is provided to apply function
**Issue :** #150
=> Handle error when an empty path is provided to apply function

packages/immutadot/src/path/consts.js, packages/immutadot/src/path/toPath.js, packages/immutadot/src/path/toPath.spec.js
=> ✨ Parse list notation

packages/immutadot/src/path/apply.js, packages/immutadot/src/path/apply.spec.js, packages/immutadot/src/path/utils.js, packages/immutadot/src/path/utils.spec.js
=> apply: Handle list notation

packages/immutadot/src/path/toPath.js, packages/immutadot/src/path/toPath.spec.js
=> Enhance toPath consistency on incomplete notations

packages/immutadot-lodash/package.json
=> Peer dependencies instead of dependencies in immutadot-lodash

.babelrc, misc/generate-flow.js, packages/immutadot-lodash/package.json, packages/immutadot/package.json
=> Use temporary merged source directory

packages/immutadot/src/flow/flow.js, packages/immutadot/src/path/apply.js, packages/immutadot/src/path/utils.js
=> fix curried operations not unary

packages/immutadot/src/core/flow.js, packages/immutadot/src/core/flow.spec.js, packages/immutadot/src/core/index.js, packages/immutadot/src/flow/index.js, packages/immutadot/src/index.js, packages/immutadot/src/util/lang.js, packages/immutadot/src/util/lang.spec.js
=> Move flow to core namespace and allow all non function args

packages/immutadot-lodash/.npmignore, packages/immutadot-lodash/package.json, packages/immutadot/.npmignore, packages/immutadot/package.json
=> Update runkit examples and other info

package.json, yarn.lock
=> rollup 0.55.3

.circleci/config.yml
=> Greenkeeper no lock file update

package.json, yarn.lock
Update rollup-plugin-node-resolve to version 3.0.3
=> chore(package): update rollup-plugin-node-resolve to version 3.0.3

docs/_pages/index.md
Add getting started section in mini-site
=> Add getting started section in mini-site

package.json, packages/immutadot-benchmark/package.json, packages/immutadot-lodash/package.json, packages/immutadot/package.json, yarn.lock
close #267
close #268
close #269
close #270
close #271
close #272
=> :arrow_up: Upgrade dependencies

README.md
Add bundles to documentation
**Issue :** #224
=> Add bundles to documentation

packages/immutadot-parser/src/toPath.spec.js, packages/immutadot-parser/src/utils.js, packages/immutadot/src/core/flow.spec.js, packages/immutadot/src/path/apply.js, packages/immutadot/src/path/apply.spec.js, packages/immutadot/src/path/utils.js
Add support of negative indexes in array notation
**Issue :** #169
=> Add support of negative indexes in array notation

packages/immutadot/src/core/apply.js, packages/immutadot/src/core/get.js, packages/immutadot/src/core/get.spec.js, packages/immutadot/src/core/set.js, packages/immutadot/src/core/update.js, packages/immutadot/src/lang/add.js, packages/immutadot/src/path/apply.js
I wrote a new `apply` based on `curry` and `nav` and used it on `set`.
=> PoC new apply on get, set, update and add

packages/immutadot/src/nav/nav.spec.js, packages/immutadot/src/nav/propsNav.js
=> :bug: Fix prop list navigation

packages/immutadot/src/nav/sliceNav.js, packages/immutadot/src/nav/sliceNav.spec.js
=> :bug: Fix slice explicit 0 index

CHANGELOG.md, README.md
Add a changelog generated with [gitmoji-changelog](https://github.com/frinyvonnick/gitmoji-changelog)
=> :tada: Add a changelog
